version: '3.8'
services:
  querybot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_PATH=/app/app/db/demo.sqlite
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./app/db:/app/app/db
